sylius_resource:
    resources:
        app.store:
            classes:
                model: App\Entity\Store
                form: App\Form\Type\StoreType

sylius_order:
    resources:
        order:
            classes:
                repository: App\Repository\OrderRepository
