winzou_state_machine:
    sylius_product_review:
        transitions:
            accept_again:
                from: ['rejected']
                to: accepted
        callbacks:
            guard:
                protectAccept:
                    on: ['accept']
                    do: ['App\Checker\TrustedAuthorChecker', 'check']
                    args: ['object']
    sylius_order_checkout:
        class: "%sylius.model.order.class%"
        property_path: checkoutState
        graph: sylius_order_checkout
        state_machine_class: "%sylius.state_machine.class%"
        states:
            cart: ~
            shipping_selected: ~
            shipping_skipped: ~
            payment_skipped: ~
            payment_selected: ~
            addressed: ~
            completed: ~
        transitions:
            select_shipment_and_payment:
                from: [cart, addressed, shipping_selected, shipping_skipped, payment_selected, payment_skipped]
                to: payment_selected
            skip_shipping:
                from: [cart, addressed, shipping_selected, shipping_skipped, payment_selected, payment_skipped]
                to: shipping_skipped
            select_shipping:
                from: [cart, addressed, shipping_selected, shipping_skipped, payment_selected, payment_skipped]
                to: shipping_selected
            skip_payment:
                from: [shipping_selected, shipping_skipped]
                to: payment_skipped
            select_payment:
                from: [payment_selected, shipping_skipped, shipping_selected]
                to: payment_selected
            address:
                from: [addressed, payment_selected, payment_skipped]
                to: addressed
            complete:
                from: [addressed]
                to: completed
        #            address:
        #                from: [cart, addressed, shipping_selected, shipping_skipped, payment_selected, payment_skipped]
        #                to: addressed
        #            skip_shipping:
        #                from: [addressed]
        #                to: shipping_skipped
        #            select_shipping:
        #                from: [addressed, shipping_selected, payment_selected, payment_skipped]
        #                to: shipping_selected
        #            skip_payment:
        #                from: [shipping_selected, shipping_skipped]
        #                to: payment_skipped
        #            select_payment:
        #                from: [payment_selected, shipping_skipped, shipping_selected]
        #                to: payment_selected
        #            complete:
        #                from: [payment_selected, payment_skipped]
        #                to: completed
        callbacks:
            after:
                sylius_process_cart:
                    on: ["select_shipping", "address", "select_payment", "skip_shipping", "skip_payment"]
                    do: ["@sylius.order_processing.order_processor", "process"]
                    args: ["object"]
                sylius_create_order:
                    on: ["complete"]
                    do: ["@sm.callback.cascade_transition", "apply"]
                    args: ["object", "event", "'create'", "'sylius_order'"]
                sylius_save_checkout_completion_date:
                    on: ["complete"]
                    do: ["object", "completeCheckout"]
                    args: ["object"]
                sylius_skip_shipping:
                    on: ["address"]
                    do: ["@sylius.state_resolver.order_checkout", "resolve"]
                    args: ["object"]
                    priority: 1
                sylius_skip_payment:
                    on: ["select_shipping"]
                    do: ["@sylius.state_resolver.order_checkout", "resolve"]
                    args: ["object"]
                    priority: 1
                sylius_control_payment_state:
                    on: ["complete"]
                    do: ["@sylius.state_resolver.order_payment", "resolve"]
                    args: ["object"]
                sylius_control_shipping_state:
                    on: ["complete"]
                    do: ["@sylius.state_resolver.order_shipping", "resolve"]
                    args: ["object"]
