winzou_state_machine:
    sylius_product_review:
        transitions:
            accept_again:
                from: ['rejected']
                to: accepted
        callbacks:
            guard:
                protectAccept:
                    on: ['accept']
                    do: ['App\Checker\TrustedAuthorChecker', 'check']
                    args: ['object']
    sylius_order_checkout:
        transitions:
            select_shipment_and_payment:
                from: [cart, addressed, shipping_selected, shipping_skipped, payment_selected, payment_skipped]
                to: payment_selected
        callbacks:
            after:
                sylius_process_cart:
                    on: ["select_shipping", "address", "select_payment", "skip_shipping", "skip_payment", "select_shipment_and_payment"]
                    do: ["@sylius.order_processing.order_processor", "process"]
                    args: ["object"]
