winzou_state_machine:
    sylius_product_review:
        transitions:
            accept_again:
                from: ['rejected']
                to: accepted
        callbacks:
            guard:
                protectAccept:
                    on: ['accept']
                    do: ['App\Checker\TrustedAuthorChecker', 'check']
                    args: ['object']
