sylius_admin:
    resource: "@SyliusAdminBundle/Resources/config/routing.yml"
    prefix: /admin

app_store:
    resource: |
        alias: app.store
        section: admin
        except: ['show', 'update']
        redirect: update
        templates: "@SyliusAdmin//Crud"
        grid: app_admin_store
    type: sylius.resource
    prefix: /admin

app_admin_store_update:
    path: '/admin/stores/{id}/edit'
    methods: ['GET', 'PUT', 'PATCH']
    defaults:
        _controller: app.controller.store:updateAction
        _sylius:
            section: admin
            redirect: app_admin_store_index
            template: '@SyliusAdmin\Crud\update.html.twig'

app_admin_product_review_accept_again:
    path: '/admin/product-reviews/{id}/accept-again'
    methods: ['PUT']
    defaults:
        _controller: sylius.controller.product_review:applyStateMachineTransitionAction
        _sylius:
            section: admin
            state_machine:
                transition: accept_again
                graph: sylius_product_review
